Repository psantosh16/Advance-Parking-Management-System, pull requests merged in 2023-08, with the labels that each got.

#8 Home page
  assets/images/car.png
  assets/images/landing_page3.jpeg
  assets/images/landing_page4.jpeg
  assets/images/person.png
  assets/images/wallet.png
  lib/GlobalState/drawer_controller.dart
  lib/Pages/Screens/Home/drawer_widget.dart
  lib/Pages/Screens/Home/home_page.dart
  lib/Pages/Screens/Map/map_page.dart
  lib/Pages/Screens/Notification/notification_page.dart
  lib/Pages/Screens/Payment/wallet_page.dart
  lib/Pages/Screens/Recipt/recipet_page.dart
  lib/Pages/Screens/home_page.dart
  lib/Pages/Screens/screen_page.dart
  lib/Pages/Screens/settings_page.dart
  lib/Pages/auth/register_page.dart
  lib/Theme/color_theme.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: bug

#13 booking slots onclick function
  lib/GlobalState/slotbutton.dart
  lib/Pages/Screens/Booking/bookingbody.dart
  lib/Pages/Screens/Booking/bookingpage.dart
  lib/Pages/Screens/Booking/slots.dart
Labels: enhancement

#18 Animation added | MapPage
  lib/Pages/Screens/Map/generate_map.dart
  lib/Pages/Screens/Map/map_page.dart
Labels: enhancement

#16 minor homescreen ui changes such as icons
  android/app/src/main/res/drawable-hdpi/splash.png
  android/app/src/main/res/drawable-mdpi/splash.png
  android/app/src/main/res/drawable-xhdpi/splash.png
  android/app/src/main/res/drawable-xxhdpi/splash.png
  android/app/src/main/res/drawable-xxxhdpi/splash.png
  assets/images/Plogo.png
  assets/images/bill.png
  assets/images/car.png
  assets/images/ewallet.png
  assets/images/wallet.png
  assets/images/wcar.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png
  lib/GlobalState/slotbutton.dart
  lib/Pages/Screens/Booking/slots.dart
  lib/Pages/Screens/Home/home_page.dart
Labels: enhancement, Ready

#19 Home page updates
  assets/images/bill.png
  assets/images/car.png
  assets/images/ewallet.png
  assets/images/homeScreen.webp
  assets/images/wallet.png
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  lib/Pages/Screens/Home/drawer_widget.dart
  lib/Pages/Screens/Home/dump.dart
  lib/Pages/Screens/Home/home_page.dart
  lib/Pages/Screens/screen_page.dart
  lib/main.dart
  pubspec.lock
Labels: enhancement, Ready

#20 "Fixed keyboard behavior and scrolling issue in RegisterPage and register ui changes"
  android/app/build.gradle
  android/app/google-services.json
  android/build.gradle
  ios/Runner/GoogleService-Info.plist
  lib/GlobalState/slotbutton.dart
  lib/Pages/Screens/Booking/bookingpage.dart
  lib/Pages/Screens/Booking/slots.dart
  lib/Pages/auth/register_page.dart
  pubspec.lock
Labels: Ready

#22 parking controller updated
  lib/GlobalState/User Booking/user_booking.dart
  lib/GlobalState/User Booking/user_booking_controller.dart
  lib/GlobalState/parking_controller.dart
  lib/Pages/Screens/Map/generate_map.dart
  lib/Pages/Screens/Map/map_page.dart
  lib/Pages/Screens/Notification/notification_page.dart
  lib/Pages/Screens/screen_page.dart
Labels: enhancement, Ready

#23 slot page and register page
  assets/images/aadhaar.png
  lib/GlobalState/provider/slotbutton.dart
  lib/GlobalState/slotbutton.dart
  lib/Pages/Screens/Booking/bookingpage.dart
  lib/Pages/Screens/Booking/slots.dart
  lib/Pages/auth/register_page.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: Ready

#24 Profile Page added
  lib/Pages/Screens/Home/drawer_widget.dart
  lib/Pages/Screens/Home/dump.dart
  lib/Pages/Screens/Home/home_page.dart
  lib/Pages/Screens/Map/map_page.dart
  lib/Pages/Screens/Profile/profile_model.dart
  lib/Pages/Screens/Profile/profile_page.dart
  lib/main.dart
  pubspec.lock
Labels: enhancement

#26 Map Fetching done
  ios/Podfile.lock
  lib/GlobalState/parking_controller.dart
  lib/GlobalState/provider/slotbutton.dart
  lib/Pages/Screens/Booking/bookingpage.dart
  lib/Pages/Screens/Booking/slots.dart
  lib/Pages/Screens/Map/map_page.dart
  lib/Pages/Screens/MapPage/map_pages.dart
  lib/Pages/Screens/Payment/wallet_page.dart
  lib/Pages/Screens/screen_page.dart
  lib/main.dart
  pubspec.lock
Labels: Ready
